version: "3"

services: 
    app:
        build: .
        command: npm start
        ports: 
            - "8081:8081"
        volumes: 
            - .:/home/Documentos/Projeto/Teste_Watson/Docker/api/Dockerfile